groups:
- name: all
  jobs:
  - populate-or-rotate-vault
  - deploy
  - smoke-tests
  - acceptance-tests
  - push-apps-manager
  - notifications
  - notifications-ui
  - autoscaling
  - autoscaling-register-broker
  - load-vault-properties
  - update-pipelines
- name: vault-interactions
  jobs:
  - populate-or-rotate-vault
  - load-vault-properties
- name: deploy
  jobs:
  - deploy
- name: tests
  jobs:
  - smoke-tests
  - acceptance-tests
- name: errands
  jobs:
  - push-apps-manager
  - notifications
  - notifications-ui
  - autoscaling
  - autoscaling-register-broker

resources:
- name: daily
  type: time
  source: {interval: 24h}
- name: {{product-slug}}
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pivnet-api-token}}
    product_slug: {{product-slug}}
    product_version: {{product-version}}
    sort_by: semver
- name: every-4hrs
  type: time
  source: {interval: 4h}
- name: concourse-deploy-cloudfoundry
  type: git
  check_every: 4h
  source:
    uri: {{deploy-cloudfoundry-git-url}}
    private_key: {{git-private-key}}
    branch: master
- name: omg-cli
  type: github-release
  check_every: 4h
  source:
    user: enaml-ops
    repository: omg-cli
- name: ert-plugin
  type: github-release
  check_every: 4h
  source:
    user: enaml-ops
    repository: ert-plugin 
    pre_release: true
- name: {{deployment-name}}
  type: bosh-deployment
  source:
    ca_cert: {{bosh-cacert}}
    client_id: {{bosh-client-id}}
    client_secret: {{bosh-client-secret}}
    deployment: {{deployment-name}}
    target: {{bosh-url}}
- name: concourse-deploy-redis
  type: git
  source:
    uri: {{deploy-redis-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-p-mysql
  type: git
  source:
    uri: {{deploy-p-mysql-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-turbulence
  type: git
  source:
    uri: {{deploy-turbulence-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-chaos-loris
  type: git
  source:
    uri: {{deploy-chaos-loris-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-rabbitmq
  type: git
  source:
    uri: {{deploy-rabbitmq-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-mgmt
  type: git
  source:
    uri: {{deploy-mgmt-git-url}}
    branch: {{foundation-name}}
    private_key: {{git-private-key}}
- name: concourse-deploy-bluemedora
  type: git
  source:
    uri: {{deploy-bluemedora-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-firehose-to-loginsight
  type: git
  source:
    uri: {{deploy-firehose-to-loginsight-git-url}}
    private_key: {{git-private-key}}
- name: concourse-deploy-spring-services
  type: git
  source:
    uri: {{deploy-spring-services-git-url}}
    private_key: {{git-private-key}}
- name: stemcells
  type: pivnet
  source:
    api_token: {{pivnet-api-token}}
    product_slug: stemcells
    product_version: {{stemcell-version}}
- name: cf-version
  type: concourse-version-resource

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource

jobs:
- name: load-vault-properties
  plan: 
    - aggregate:
      - get: concourse-deploy-cloudfoundry
    - task: load-vault-properties 
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/populate-vault-deployment-properties.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_HASH_MISC: {{vault-hash-misc}}
          VAULT_TOKEN: {{vault-token}}
          VAULT_PROPERTIES_JSON: {{vault-json-string}}
          BOSH_CLIENT_SECRET: {{bosh-pass}}
          BOSH_CACERT: {{bosh-cacert}}
        inputs:
        - name: concourse-deploy-cloudfoundry
    - put: cf-version
- name: populate-or-rotate-vault
  plan:
    - aggregate:
      - get: cf-version
        passed: [load-vault-properties]
        trigger: true
      - get: concourse-deploy-cloudfoundry
      - get: omg-cli
        params:
          globs:
          - omg-linux
      - get: ert-plugin
        params:
          globs:
          - ert-1-8-linux
    - task: populate-or-rotate
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: allomov/deploy-worker
            tags: v2.0
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/populate-or-rotate-vault.sh
        params:
          PRODUCT_PLUGIN: {{product-plugin}}
          SYSTEM_DOMAIN: {{system-domain}}
          VAULT_ADDR: {{vault-addr}}
          VAULT_HASH_IP: {{vault-hash-ip}}
          VAULT_HASH_HOSTVARS: {{vault-hash-hostvars}}
          VAULT_HASH_KEYCERT: {{vault-hash-keycert}}
          VAULT_HASH_MISC: {{vault-hash-misc}}
          VAULT_HASH_PASSWORD: {{vault-hash-password}}
          VAULT_TOKEN: {{vault-token}}
          STEMCELL_VERSION: {{stemcell-version}}
          UAA_LDAP_PASSWORD: {{uaa-ldap-password}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        - name: omg-cli
        - name: ert-plugin
        outputs:
- name: deploy
  plan:
    - aggregate:
      - get: cf-version
        passed: [populate-or-rotate-vault]
        trigger: true
      - get: concourse-deploy-cloudfoundry
      - get: omg-cli
        params:
          globs:
          - omg-linux
      - get: ert-plugin
        params:
          globs:
          - ert-1-8-linux
      - get: {{product-slug}}
        params:
          globs:
          - cf-*
      - get: stemcells
        params:
          globs:
          - {{stemcell-cpi-glob}}
    - task: generate-manifest
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/generate-pcf-manifest.sh
        params:
          BOSH_CLIENT: {{bosh-user}}
          BOSH_CLIENT_SECRET: {{bosh-pass}}
          BOSH_CACERT: {{bosh-cacert}}
          PRODUCT_PLUGIN: {{product-plugin}}
          SKIP_HAPROXY: {{skip-haproxy}}
          STEMCELL_VERSION: {{stemcell-version}}
          VAULT_ADDR: {{vault-addr}}
          VAULT_HASH_IP: {{vault-hash-ip}}
          VAULT_HASH_HOSTVARS: {{vault-hash-hostvars}}
          VAULT_HASH_KEYCERT: {{vault-hash-keycert}}
          VAULT_HASH_MISC: {{vault-hash-misc}}
          VAULT_HASH_PASSWORD: {{vault-hash-password}}
          VAULT_TOKEN: {{vault-token}}
          OUTPUT_DIR: manifest
          UAA_LDAP_PASSWORD: {{uaa-ldap-password}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        - name: omg-cli
        - name: ert-plugin
        outputs:
        - name: manifest
          path: ""
    - task: extract-tile
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/extract-tile.sh
        params:
          PRODUCT_DIR: {{product-slug}}
          OUTPUT_DIR: product-extracted
        inputs:
        - name: concourse-deploy-cloudfoundry
        - name: {{product-slug}}
        outputs:
        - name: product-extracted
          path: ""
    - put: {{deployment-name}}
      params:
        manifest: manifest/deployment.yml
        stemcells:
        - stemcells/bosh-stemcell*.tgz
        releases:
        - product-extracted/releases/cf*.tgz
        - product-extracted/releases/diego*.tgz
        - product-extracted/releases/garden-runc*.tgz
        - product-extracted/releases/cflinuxfs2*.tgz
        - product-extracted/releases/etcd*.tgz
        - product-extracted/releases/mysql-backup*.tgz
        - product-extracted/releases/push-apps-manager*.tgz
        - product-extracted/releases/cf-autoscaling*.tgz
        - product-extracted/releases/notifications*.tgz
- name: smoke-tests
  plan:
    - aggregate:
      - get: every-4hrs
        trigger: true
      - get: concourse-deploy-cloudfoundry
      - get: {{deployment-name}}
        passed: [deploy]
    - task: smoke-tests
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/run-errand.sh
        params:
          BOSH_CACERT: {{bosh-cacert}}
          BOSH_CLIENT: {{bosh-client-id}}
          BOSH_CLIENT_SECRET: {{bosh-client-secret}}
          BOSH_DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_ERRAND: smoke-tests
          BOSH_TARGET: {{bosh-url}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        outputs:
- name: acceptance-tests
  plan:
    - aggregate:
      - get: daily
        trigger: true
      - get: concourse-deploy-cloudfoundry
      - get: {{deployment-name}}
        passed: [deploy]
    - task: acceptance-tests
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/run-errand.sh
        params:
          BOSH_CACERT: {{bosh-cacert}}
          BOSH_CLIENT: {{bosh-client-id}}
          BOSH_CLIENT_SECRET: {{bosh-client-secret}}
          BOSH_DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_ERRAND: acceptance-tests
          BOSH_TARGET: {{bosh-url}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        outputs:
- name: push-apps-manager
  plan:
    - aggregate:
      - get: concourse-deploy-cloudfoundry
      - get: {{deployment-name}}
        passed: [deploy]
        trigger: true
    - task: push-apps-manager
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/run-errand.sh
        params:
          BOSH_CACERT: {{bosh-cacert}}
          BOSH_CLIENT: {{bosh-client-id}}
          BOSH_CLIENT_SECRET: {{bosh-client-secret}}
          BOSH_DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_ERRAND: push-apps-manager
          BOSH_TARGET: {{bosh-url}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        outputs:
- name: notifications
  plan:
    - aggregate:
      - get: concourse-deploy-cloudfoundry
      - get: {{deployment-name}}
        passed: [push-apps-manager]
        trigger: true
    - task: notifications
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/run-errand.sh
        params:
          BOSH_CACERT: {{bosh-cacert}}
          BOSH_CLIENT: {{bosh-client-id}}
          BOSH_CLIENT_SECRET: {{bosh-client-secret}}
          BOSH_DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_ERRAND: notifications
          BOSH_TARGET: {{bosh-url}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        outputs:
- name: notifications-ui
  plan:
    - aggregate:
      - get: concourse-deploy-cloudfoundry
      - get: {{deployment-name}}
        passed: [notifications]
        trigger: true
    - task: notifications-ui
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/run-errand.sh
        params:
          BOSH_CACERT: {{bosh-cacert}}
          BOSH_CLIENT: {{bosh-client-id}}
          BOSH_CLIENT_SECRET: {{bosh-client-secret}}
          BOSH_DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_ERRAND: notifications-ui
          BOSH_TARGET: {{bosh-url}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        outputs:
- name: autoscaling
  plan:
    - aggregate:
      - get: concourse-deploy-cloudfoundry
      - get: {{deployment-name}}
        passed: [notifications-ui]
        trigger: true
    - task: autoscaling
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/run-errand.sh
        params:
          BOSH_CACERT: {{bosh-cacert}}
          BOSH_CLIENT: {{bosh-client-id}}
          BOSH_CLIENT_SECRET: {{bosh-client-secret}}
          BOSH_DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_ERRAND: autoscaling
          BOSH_TARGET: {{bosh-url}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        outputs:
- name: autoscaling-register-broker
  plan:
    - aggregate:
      - get: concourse-deploy-cloudfoundry
      - get: {{deployment-name}}
        passed: [autoscaling]
        trigger: true
    - task: autoscaling-register-broker
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/deploy-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/run-errand.sh
        params:
          BOSH_CACERT: {{bosh-cacert}}
          BOSH_CLIENT: {{bosh-client-id}}
          BOSH_CLIENT_SECRET: {{bosh-client-secret}}
          BOSH_DEPLOYMENT_NAME: {{deployment-name}}
          BOSH_ERRAND: autoscaling-register-broker
          BOSH_TARGET: {{bosh-url}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        outputs:
- name: update-pipelines
  plan:
    - aggregate:
      - get: {{deployment-name}}
        passed: [autoscaling-register-broker]
        trigger: true
      - get: concourse-deploy-cloudfoundry
      - get: concourse-deploy-redis
      - get: concourse-deploy-p-mysql
      - get: concourse-deploy-turbulence
      - get: concourse-deploy-chaos-loris
      - get: concourse-deploy-rabbitmq
      - get: concourse-deploy-mgmt
      - get: concourse-deploy-bluemedora
      - get: concourse-deploy-firehose-to-loginsight
      - get: concourse-deploy-spring-services
    - task: update-pipelines
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/bosh-worker
        run:
          path: concourse-deploy-cloudfoundry/ci/tasks/update-pipelines.sh
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          FOUNDATION_NAME: {{foundation-name}}
          BOSH_URL: {{bosh-url}}
          CONCOURSE_URL: {{concourse-url}}
          CONCOURSE_USER: {{concourse-user}}
          CONCOURSE_PASSWORD: {{concourse-pass}}
          DEPLOYMENT_NAME: {{deployment-name}}
          SYSLOG_ADDRESS: {{syslog-address}}
          SYSTEM_DOMAIN: {{system-domain}}
          PIVNET_API_TOKEN: {{pivnet-api-token}}
          PCF_SERVICES_STATIC: {{pcf-services-static}}
          DEPLOY_REDIS_GIT_URL: {{deploy-redis-git-url}}
          DEPLOY_P_MYSQL_GIT_URL: {{deploy-p-mysql-git-url}}
          DEPLOY_TURBULENCE_GIT_URL: {{deploy-turbulence-git-url}}
          DEPLOY_CHAOS_LORIS_GIT_URL: {{deploy-chaos-loris-git-url}}
          DEPLOY_RABBITMQ_GIT_URL: {{deploy-rabbitmq-git-url}}
          DEPLOY_MGMT_GIT_URL: {{deploy-mgmt-git-url}}
          DEPLOY_BLUEMEDORA_GIT_URL: {{deploy-bluemedora-git-url}}
          DEPLOY_FIREHOSE_TO_LOGINSIGHT_GIT_URL: {{deploy-firehose-to-loginsight-git-url}}
          DEPLOY_SPRING_SERVICES_GIT_URL: {{deploy-spring-services-git-url}}
          GIT_PRIVATE_KEY: {{git-private-key}}
          CONFIGSERVER_GIT_REPO_URL: {{configserver-git-repo-url}}
          CONFIGSERVER_GIT_REPO_USERNAME: {{configserver-git-repo-user}}
          CONFIGSERVER_GIT_REPO_PASSWORD: {{configserver-git-repo-password}}
        inputs:
        - name: concourse-deploy-cloudfoundry
        - name: concourse-deploy-redis
        - name: concourse-deploy-turbulence
        - name: concourse-deploy-chaos-loris
        - name: concourse-deploy-rabbitmq
        - name: concourse-deploy-mgmt
        - name: concourse-deploy-p-mysql
        - name: concourse-deploy-bluemedora
        - name: concourse-deploy-firehose-to-loginsight
        - name: concourse-deploy-spring-services
